In [1]:
import numpy as np
import pandas as pd

In [2]:
content = pd.read_csv('cora/cora.content', delimiter='\t', header=None, index_col=0).sort_values(by=0)
content

1     2     3     4     5     6     7     8     9     10    ...  \
0                                                                    ...   
35          0     0     0     0     0     0     0     0     0     0  ...   
40          0     0     0     0     0     0     0     0     0     0  ...   
114         0     0     0     0     0     0     0     1     0     0  ...   
117         0     0     0     0     0     0     0     0     0     0  ...   
128         0     1     0     0     0     0     0     0     0     0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
1154500     0     0     0     0     0     0     0     0     0     0  ...   
1154520     0     0     0     0     0     0     0     0     0     0  ...   
1154524     0     0     0     0     0     0     0     0     0     0  ...   
1154525     0     0     0     0     0     0     0     0     0     0  ...   
1155073     0     0     0     0     0     0     0     0     0     0  ...   

         1425  1426  1427  1428  1429  1430  1431  1432  1433  \
0                                                               
35          0     0     0     0     0     0     0     0     0   
40          0     0     0     0     0     0     0     0     0   
114         0     0     0     0     0     0     0     0     0   
117         0     0     0     0     0     0     0     0     0   
128         0     0     0     0     0     0     0     0     0   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   
1154500     0     0     0     0     0     0     0     0     0   
1154520     0     0     0     0     0     0     0     0     0   
1154524     0     0     0     0     0     0     0     0     0   
1154525     0     0     0     0     0     0     0     0     0   
1155073     0     0     0     0     0     0     0     0     0   

                           1434  
0                                
35           Genetic_Algorithms  
40           Genetic_Algorithms  
114      Reinforcement_Learning  
117      Reinforcement_Learning  
128      Reinforcement_Learning  
...                         ...  
1154500              Case_Based  
1154520         Neural_Networks  
1154524           Rule_Learning  
1154525           Rule_Learning  
1155073           Rule_Learning  

[2708 rows x 1434 columns]

In [3]:
features = content[range(1, 1434)].to_numpy(dtype=float)
V, M = features.shape
features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
klasses = pd.factorize(content[1434])[0]
K = klasses.max()+1
klasses

array([0, 0, 1, ..., 3, 3, 3])

In [5]:
cites = np.vectorize(content.index.get_loc)(np.loadtxt('cora/cora.cites', dtype=int))
E = cites.shape[0]
cites

array([[   0,   21],
       [   0,  905],
       [   0,  906],
       ...,
       [1874, 2586],
       [1876, 1874],
       [1897, 2707]])

In [6]:
print(f"Number of nodes: {V}")
print(f"Number of edges: {E}")
print(f"Number of features: {M}")
print(f"Number of classes: {K}")

Number of nodes: 2708
Number of edges: 5429
Number of features: 1433
Number of classes: 7


In [7]:
adj = np.zeros((V,V))
adj[cites[:,1],cites[:,0]] = 1
# np.set_printoptions(np.inf)
adj

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])